"""Information holder file for laziness sake."""
marketSegments = [
    "S&P BSE Diversified Financials Revenue Growth Index",
    "S&P BSE SENSEX",
    "S&P BSE 100",
    "S&P BSE 100 ESG Index",
    "S&P BSE 100 LargeCap TMC Index",
    "S&P BSE 150 MidCap Index",
    "S&P BSE 200",
    "S&P BSE 250 LargeMidCap Index",
    "S&P BSE 250 SmallCap Index",
    "S&P BSE 400 MidSmallCap Index",
    "S&P BSE 500",
    "S&P BSE AllCap",
    "S&P BSE AUTO",
    "S&P BSE BANKEX",
    "S&P BSE Basic Materials",
    "S&P BSE Bharat 22 Index",
    "S&P BSE CAPITAL GOODS",
    "S&P BSE CARBONEX",
    "S&P BSE Consumer Discretionary Goods & Services",
    "S&P BSE CONSUMER DURABLES",
    "S&P BSE CPSE",
    "S&P BSE Dividend Stability Index",
    "S&P BSE DOLLEX 100",
    "S&P BSE DOLLEX 200",
    "S&P BSE DOLLEX 30",
    "S&P BSE Energy",
    "S&P BSE Enhanced Value Index",
    "S&P BSE Fast Moving Consumer Goods",
    "S&P BSE Finance",
    "S&P BSE GREENEX",
    "S&P BSE Healthcare",
    "S&P BSE India Infrastructure Index",
    "S&P BSE India Manufacturing Index",
    "S&P BSE Industrials",
    "S&P BSE Information Technology",
    "S&P BSE IPO",
    "S&P BSE LargeCap",
    "S&P BSE Low Volatility Index",
    "S&P BSE METAL",
    "S&P BSE MidCap",
    "S&P BSE MidCap Select Index",
    "S&P BSE Momentum Index",
    "S&P BSE OIL & GAS",
    "S&P BSE POWER",
    "S&P BSE Private Banks Index",
    "S&P BSE PSU",
    "S&P BSE Quality Index",
    "S&P BSE REALTY",
    "S&P BSE SENSEX 50",
    "S&P BSE SENSEX Next 50",
    "S&P BSE SmallCap",
    "S&P BSE SmallCap Select Index",
    "S&P BSE SME IPO",
    "S&P BSE TECK",
    "S&P BSE Telecom",
    "S&P BSE Utilities"
]